"""vote unvote activities added

Revision ID: 1f3adfdb8b1c
Revises: ce2e8f83a8d2
Create Date: 2025-01-24 20:47:13.859653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f3adfdb8b1c'
down_revision: Union[str, None] = 'ce2e8f83a8d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_votes',
    sa.Column('user_username', sa.String(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['user_username'], ['users.username'], )
    )
    op.drop_table('post_likes')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_likes',
    sa.Column('user_username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='post_likes_post_id_fkey'),
    sa.ForeignKeyConstraint(['user_username'], ['users.username'], name='post_likes_user_username_fkey')
    )
    op.drop_table('post_votes')
    # ### end Alembic commands ###
