"""votes_count column added

Revision ID: 245577839ed9
Revises: 1f3adfdb8b1c
Create Date: 2025-01-24 21:03:52.917212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '245577839ed9'
down_revision: Union[str, None] = '1f3adfdb8b1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('votes_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'votes_count')
    # ### end Alembic commands ###
