"""empty message

Revision ID: 30cb967fae47
Revises: e4115366ec30
Create Date: 2025-02-18 15:34:10.113968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30cb967fae47'
down_revision: Union[str, None] = 'e4115366ec30'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_interest_association',
    sa.Column('profile_id', sa.Integer(), nullable=True),
    sa.Column('interest_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], ),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], )
    )
    op.drop_table('profile_interest_association')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profile_interest_association',
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('interest_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['interest_id'], ['interests.id'], name='profile_interest_association_interest_id_fkey'),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.id'], name='profile_interest_association_profile_id_fkey')
    )
    op.drop_table('user_interest_association')
    # ### end Alembic commands ###
