"""add is_online attribute

Revision ID: 6cf731c192af
Revises: 11c75a941854
Create Date: 2025-02-28 08:47:13.630134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6cf731c192af'
down_revision: Union[str, None] = '11c75a941854'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_active', sa.DateTime(), nullable=True))
    op.drop_column('users', 'last_seen')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('users', 'last_active')
    # ### end Alembic commands ###
