"""is_active attribute added

Revision ID: a2f3128f5224
Revises: c2e85900af9c
Create Date: 2025-02-25 20:29:25.885913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2f3128f5224'
down_revision: Union[str, None] = 'c2e85900af9c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('similarities', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('similarities', 'is_active')
    # ### end Alembic commands ###
