"""empty message

Revision ID: d6a4031b56b0
Revises: 30cb967fae47
Create Date: 2025-02-18 15:35:43.895233

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6a4031b56b0'
down_revision: Union[str, None] = '30cb967fae47'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_interest_association_profile_id_fkey', 'user_interest_association', type_='foreignkey')
    op.create_foreign_key(None, 'user_interest_association', 'users', ['profile_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_interest_association', type_='foreignkey')
    op.create_foreign_key('user_interest_association_profile_id_fkey', 'user_interest_association', 'profiles', ['profile_id'], ['id'])
    # ### end Alembic commands ###
