"""empty message

Revision ID: e687f04e8d20
Revises: 3a747ecfa05c
Create Date: 2025-02-15 07:00:04.529601

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e687f04e8d20'
down_revision: Union[str, None] = '3a747ecfa05c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('bio', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'bio')
    # ### end Alembic commands ###
