from enum import Enum

class Gender(str, Enum):
    MALE = "male"
    FEMALE = "female"
    OTHER = "others"
    NO_SELECTED = "no gender selected"

# class InterestEnum(str, Enum):
#     Reading = "Reading"
#     Traveling = "Traveling"
#     Cooking = "Cooking"
#     Sports = "Sports"
#     Music = "Music"
#     Movies = "Movies"
#     Gaming = "Gaming"
#     Fitness = "Fitness"
#     Art = "Art"
#     Photography = "Photography"
#     Writing = "Writing"
#     Dancing = "Dancing"
#     Gardening = "Gardening"
#     Hiking = "Hiking"
#     Cycling = "Cycling"
#     Yoga = "Yoga"
#     Meditation = "Meditation"
#     Singing = "Singing"
#     Technology = "Technology"
#     Fashion = "Fashion"
#     Pet = "Pet"
#     Nature = "Nature"
#     Science = "Science"
#     History = "History"
#     Languages = "Languages"
#     Coffee = "Coffee"
#     Tea = "Tea"
#     Camping = "Camping"
#     Coding = "Coding"
